name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /var/www/your-repo
          git pull origin main
          # Add any additional commands (e.g., restart services, npm install)
          sudo systemctl restart nginx
